/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.DAO.HoaDonDAO;
import com.DAO.SanPhamDAO;
import com.helper.DateHelper;
import com.helper.DialogHelper;
import com.helper.ShareHelper;
import com.model.HoaDon;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham Nguyen Hoang Anh
 */
public class HoaDonJFrame extends javax.swing.JFrame {

    SanPhamDAO spdao = new SanPhamDAO();
    public HoaDonJFrame() {
        initComponents();
        init();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }
    
    public boolean checkloi(){
       try{
          if(this.txtSoHD.getText().equals("")){
            lblHD.setText("Chưa nhập Số Hóa Đơn!");         
              txtSoHD.requestFocus();
              return false;
          }else{
              lblHD.setText(null);      
          }
          if(this.txtMakh.getText().equals("")){
            lblMakh.setText("Chưa nhập Mã Khách Hàng!");
              txtMakh.requestFocus();
              return false;
          }else{
              lblMakh.setText(null);
          }
          if(this.txtManv.getText().equals("")){
            lblManv.setText("Chưa nhập Mã Nhân Viên!");
              txtManv.requestFocus();
              return false;
          }else{
              lblManv.setText(null);
          }
          if(this.txtMasp.getText().equals("")){
            lblMasp.setText("Chưa nhập Mã Sản Phẩm!");        
              txtMasp.requestFocus();
              return false;
          }else{
              lblMasp.setText(null);
          }
          if(this.txtSL.getText().equals("")){
            lblsl.setText("Chưa nhập Số Lượng!");    
              txtSL.requestFocus();
              return false;
          }else{
              lblsl.setText(null);
          }
          if(this.txtNGLHD.getText().equals("")){
            lblNlhd.setText("Chưa nhập Ngày Lập Hóa Đơn!");            
              txtNGLHD.requestFocus();
              return false;
          }else{
              lblNlhd.setText(null);
          }
          if(this.txtGhichu.getText().equals("")){
            lblGC.setText("Chưa nhập Ghi Chú!");             
              txtGhichu.requestFocus();
              return false;
          }else{
              lblGC.setText(null);
          }
   }catch(Exception e){
                e.printStackTrace();
                return false;  
   }
       return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNGLHD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        lblHD = new javax.swing.JLabel();
        lblMakh = new javax.swing.JLabel();
        lblManv = new javax.swing.JLabel();
        lblMasp = new javax.swing.JLabel();
        lblsl = new javax.swing.JLabel();
        lblNlhd = new javax.swing.JLabel();
        lblTT = new javax.swing.JLabel();
        lblGC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGirlview = new javax.swing.JTable();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ HÓA ĐƠN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setText("Số hóa đơn");

        txtSoHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoHDKeyReleased(evt);
            }
        });

        jLabel3.setText("Mã khách hàng");

        txtMakh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMakhKeyReleased(evt);
            }
        });

        jLabel4.setText("Mã nhân viên");

        txtManv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManvKeyReleased(evt);
            }
        });

        jLabel5.setText("Mã sản phẩm");

        txtMasp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaspKeyReleased(evt);
            }
        });

        jLabel6.setText("Số lượng");

        txtSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSLKeyReleased(evt);
            }
        });

        jLabel7.setText("Ghi chú:");

        txtGhichu.setColumns(20);
        txtGhichu.setRows(5);
        txtGhichu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGhichuKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtGhichu);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel8.setText("Ngày lập hóa đơn");

        txtNGLHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGLHDKeyReleased(evt);
            }
        });

        jLabel9.setText("Tổng tiền");

        lblHD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHD.setForeground(new java.awt.Color(255, 0, 0));

        lblMakh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMakh.setForeground(new java.awt.Color(255, 0, 0));

        lblManv.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManv.setForeground(new java.awt.Color(255, 0, 0));

        lblMasp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMasp.setForeground(new java.awt.Color(255, 0, 0));

        lblsl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblsl.setForeground(new java.awt.Color(255, 0, 0));

        lblNlhd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNlhd.setForeground(new java.awt.Color(255, 0, 0));

        lblTT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTT.setForeground(new java.awt.Color(255, 0, 0));

        lblGC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGC.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnThem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnXoa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSua)
                            .addGap(18, 18, 18)
                            .addComponent(btnMoi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFirst)
                            .addGap(35, 35, 35)
                            .addComponent(btnPrev)
                            .addGap(48, 48, 48)
                            .addComponent(btnNext)
                            .addGap(41, 41, 41)
                            .addComponent(btnLast))
                        .addComponent(txtMakh)
                        .addComponent(txtManv)
                        .addComponent(jScrollPane1)
                        .addComponent(txtSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNGLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNlhd))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSL)
                                    .addComponent(txtTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                                .addComponent(lblsl)
                                .addComponent(lblTT))))
                    .addComponent(jLabel5)
                    .addComponent(lblHD)
                    .addComponent(lblMakh)
                    .addComponent(lblManv)
                    .addComponent(lblMasp)
                    .addComponent(lblGC)
                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHD)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMakh)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblManv)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMasp)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNGLHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTT)
                    .addComponent(lblNlhd))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CẬP NHẬT", jPanel1);

        tblGirlview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số hóa đơn", "Mã khách hàng", "Mã nhân viên", "Mã sản phẩm", "Số lượng", "Ngày lập HD", "Tổng tiền", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGirlview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGirlviewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGirlview);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BẢNG HÓA ĐƠN", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.load();
        this.setStatus(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(this.checkloi()){
            if(this.isvalid()){
               this.insert();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
        this.load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(this.isvalid()){
           this.update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.index = tblGirlview.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblGirlviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGirlviewMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            this.index = tblGirlview.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
                jTabbedPane1.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblGirlviewMouseClicked

    private void txtSLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyReleased
    double SoLuong = 0;
       double Tien = 0;
       try {
           SoLuong = Integer.valueOf(txtSL.getText());
        } catch (Exception e) {
        }
        double Gia = spdao.GetGiaSanPham(txtMasp.getText().toString());
        Tien = (double) Gia * SoLuong;
        txtTongtien.setText(String.valueOf(Tien));
        if(!txtSL.getText().equals("")){
           lblsl.setText(null);
      }
    }//GEN-LAST:event_txtSLKeyReleased

    private void txtSoHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoHDKeyReleased
        // TODO add your handling code here:
        if(!txtSoHD.getText().equals("")){
           lblHD.setText(null);
      }
    }//GEN-LAST:event_txtSoHDKeyReleased

    private void txtMakhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMakhKeyReleased
        // TODO add your handling code here:
        if(!txtMakh.getText().equals("")){
           lblMakh.setText(null);
      }
    }//GEN-LAST:event_txtMakhKeyReleased

    private void txtManvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManvKeyReleased
        // TODO add your handling code here:
        if(!txtManv.getText().equals("")){
           lblManv.setText(null);
      }
    }//GEN-LAST:event_txtManvKeyReleased

    private void txtMaspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaspKeyReleased
        // TODO add your handling code here:
        if(!txtMasp.getText().equals("")){
           lblMasp.setText(null);
      }
    }//GEN-LAST:event_txtMaspKeyReleased

    private void txtNGLHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGLHDKeyReleased
        // TODO add your handling code here:
        if(!txtNGLHD.getText().equals("")){
           lblNlhd.setText(null);
      }
    }//GEN-LAST:event_txtNGLHDKeyReleased

    private void txtGhichuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGhichuKeyReleased
        // TODO add your handling code here:
        if(!txtGhichu.getText().equals("")){
           lblGC.setText(null);
      }
    }//GEN-LAST:event_txtGhichuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblGC;
    private javax.swing.JLabel lblHD;
    private javax.swing.JLabel lblMakh;
    private javax.swing.JLabel lblManv;
    private javax.swing.JLabel lblMasp;
    private javax.swing.JLabel lblNlhd;
    private javax.swing.JLabel lblTT;
    private javax.swing.JLabel lblsl;
    private javax.swing.JTable tblGirlview;
    public javax.swing.JTextArea txtGhichu;
    public javax.swing.JTextField txtMakh;
    public javax.swing.JTextField txtManv;
    public javax.swing.JTextField txtMasp;
    public javax.swing.JTextField txtNGLHD;
    public javax.swing.JTextField txtSL;
    public javax.swing.JTextField txtSoHD;
    public javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
int index = 0;
    HoaDonDAO dao = new HoaDonDAO();

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

     //Bắt lỗi
    public boolean isvalid(){
        if(txtSoHD.getText().length() == 0){
            DialogHelper.alert(this, "Không được bỏ trống số hóa đơn!");
            return false;
        }
        if(txtSoHD.getText().length() < 2){
            DialogHelper.alert(this, "Số hóa đơn có ít nhất có 2 ký tự!");
            return false;
        }
        if(txtNGLHD.getText().length() < 3){
            DialogHelper.alert(this, "Ngày lập hóa đơn không nhâp đúng định dạng!");
            return false;
        }
        return true;
    }
    
    void load() {
        DefaultTableModel model = (DefaultTableModel) tblGirlview.getModel();
        model.setRowCount(0);
        try {
            List<HoaDon> list = dao.select();
            for (HoaDon tl : list) {
                Object[] row = {
                tl.getSoHD(),
                tl.getMaKH(),
                tl.getMaNV(),
                tl.getMaSP(),
                tl.getSoLuong(),
                tl.getNgLHD(),
                tl.getTriGia(),
                tl.getGhiChu(),           
            };
            model.addRow(row);
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    public boolean insert(){
        HoaDon model = getModel();
        try {
            dao.insert(model);
            this.load();
            this.clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
            return true;
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!");
        }
        return false;
    }
    
    public boolean update(){
        HoaDon model = getModel();
        try {
            dao.update(model);
            this.load();
            DialogHelper.alert(this, "Cập nhật thành công!");
            return true;
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
        return false;
    }

    public boolean delete(){
        if(DialogHelper.confirm(this, "Bạn có muốn xóa hay không?")){
            String macd = txtSoHD.getText();
            try {
                dao.delete(macd);
                this.load();
                this.clear();
                DialogHelper.alert(this, "Xóa thành công!");
                return true;
            }
            catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
        return false;
    }

    void clear(){
        this.setModel(new HoaDon());
        this.setStatus(true);
    }

    void edit() {
        try {
            int macd = (int) tblGirlview.getValueAt(this.index, 0);
            HoaDon model = dao.findById(macd);
            if(model != null){
            this.setModel(model);
            this.setStatus(false);
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void setModel(HoaDon model){
        txtSoHD.setText(String.valueOf(model.getSoHD()));
        txtMakh.setText(model.getMaKH());
        txtManv.setText(model.getMaNV());
        txtMasp.setText(model.getMaSP());
        txtSL.setText(String.valueOf(model.getSoLuong()));
        txtNGLHD.setText(model.getNgLHD());
        txtTongtien.setText(model.getTriGia());
        txtGhichu.setText(model.getGhiChu());
        lblGC.setText(null);
        lblHD.setText(null);
        lblMakh.setText(null);
        lblManv.setText(null);
        lblMasp.setText(null);
        lblNlhd.setText(null);
        lblTT.setText(null);
        lblsl.setText(null);
    }
    
    HoaDon getModel(){
        HoaDon model = new HoaDon();
        model.setMaKH(txtMakh.getText());
        model.setSoHD(Integer.parseInt(txtSoHD.getText()));
        model.setNgLHD(txtNGLHD.getText());
        model.setMaNV(txtManv.getText());
        model.setMaSP(txtMasp.getText());
        model.setSoLuong(Integer.parseInt(txtSL.getText()));
        model.setTriGia(txtTongtien.getText());
        model.setGhiChu(txtGhichu.getText());
        return model;
    }

    void setStatus(boolean insertable){
        txtSoHD.setEditable(insertable);
        btnThem.setEnabled(insertable);
        btnSua.setEnabled(!insertable);
        btnXoa.setEnabled(!insertable);
        boolean first = this.index > 0;
        boolean last = this.index < tblGirlview.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    } 
}
