/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.DAO.KhachHangDAO;
import com.helper.DateHelper;
import com.helper.DialogHelper;
import com.helper.ShareHelper;
import com.model.KhachHang;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham Nguyen Hoang Anh
 */
public class KhachHangJFrame extends javax.swing.JFrame {

    public KhachHangJFrame() {
        initComponents();
        init();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }
    
    public boolean checkloi(){
       try{
          if(this.txtMakh.getText().equals("")){
            lblMakh.setText("Chưa nhập Mã Khách Hàng!");
            
              txtMakh.requestFocus();
              return false;
          }else{
              lblMakh.setText(null);       
          }
          if(this.txtHoten.getText().equals("")){
            lblHt.setText("Chưa nhập Họ Tên Khách Hàng!");
              txtHoten.requestFocus();
              return false;
          }else{
              lblHt.setText(null);
          }
          if(this.txtDiachi.getText().equals("")){
            lblDC.setText("Chưa nhập Địa Chỉ!");
              txtDiachi.requestFocus();
              return false;
          }else{
              lblDC.setText(null);
          }
          if(this.txtSodt.getText().equals("")){
            lblSDT.setText("Chưa nhập Số Điện Thoại!");            
              txtSodt.requestFocus();
              return false;
          }else{
              lblSDT.setText(null);
          }
          if(this.txtNgaysinh.getText().equals("")){
            lblNgaySinh.setText("Chưa nhập Ngày Sinh!");           
              txtNgaysinh.requestFocus();
              return false;
          }else{
              lblNgaySinh.setText(null);
          }
   }catch(Exception e){
                e.printStackTrace();
                return false;  
   }
       return true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSodt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        txtNgaysinh = new javax.swing.JTextField();
        lblMakh = new javax.swing.JLabel();
        lblHt = new javax.swing.JLabel();
        lblDC = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGirlview = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHÁCH HÀNG");
        setMinimumSize(new java.awt.Dimension(0, 600));
        setPreferredSize(new java.awt.Dimension(658, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(629, 590));

        jLabel2.setText("Mã khách hàng");

        txtMakh.setToolTipText("");
        txtMakh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMakhKeyReleased(evt);
            }
        });

        jLabel3.setText("Họ và tên khách hàng");

        txtHoten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHotenKeyReleased(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        txtDiachi.setToolTipText("");
        txtDiachi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiachiKeyReleased(evt);
            }
        });

        jLabel5.setText("Số điện thoại");

        txtSodt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSodtKeyReleased(evt);
            }
        });

        jLabel6.setText("Ngày sinh");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        txtNgaysinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNgaysinhKeyReleased(evt);
            }
        });

        lblMakh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMakh.setForeground(new java.awt.Color(255, 0, 0));

        lblHt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHt.setForeground(new java.awt.Color(255, 0, 0));

        lblDC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDC.setForeground(new java.awt.Color(255, 0, 0));

        lblSDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(255, 0, 0));

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(txtMakh, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addComponent(txtHoten)
                        .addComponent(txtDiachi)
                        .addComponent(txtSodt)
                        .addComponent(txtNgaysinh))
                    .addComponent(lblMakh)
                    .addComponent(lblHt)
                    .addComponent(lblDC)
                    .addComponent(lblSDT)
                    .addComponent(lblNgaySinh)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoi)
                        .addGap(54, 54, 54)
                        .addComponent(btnFirst)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrev)
                        .addGap(24, 24, 24)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMakh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNgaySinh)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CẬP NHẬT", jPanel1);

        tblGirlview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Địa chỉ", "Số điện thoại", "Ngày sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGirlview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGirlviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGirlview);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.load();
        this.setStatus(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(this.checkloi()){
            if(this.isvalid()){
               this.insert();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
        this.load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(this.isvalid()){
           this.update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.index = tblGirlview.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblGirlviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGirlviewMouseClicked
            // TODO add your handling code here:
            if(evt.getClickCount() == 2){
            this.index = tblGirlview.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
                jTabbedPane1.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblGirlviewMouseClicked

    private void txtMakhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMakhKeyReleased
        // TODO add your handling code here:
        if(!txtMakh.getText().equals("")){
           lblMakh.setText(null);
      }
    }//GEN-LAST:event_txtMakhKeyReleased

    private void txtHotenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHotenKeyReleased
        // TODO add your handling code here:
        if(!txtHoten.getText().equals("")){
           lblHt.setText(null);
      }
    }//GEN-LAST:event_txtHotenKeyReleased

    private void txtDiachiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiachiKeyReleased
        // TODO add your handling code here:
        if(!txtDiachi.getText().equals("")){
           lblDC.setText(null);
      }
    }//GEN-LAST:event_txtDiachiKeyReleased

    private void txtSodtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodtKeyReleased
        // TODO add your handling code here:
        if(!txtSodt.getText().equals("")){
           lblSDT.setText(null);
      }
    }//GEN-LAST:event_txtSodtKeyReleased

    private void txtNgaysinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgaysinhKeyReleased
        // TODO add your handling code here:
        if(!txtNgaysinh.getText().equals("")){
           lblNgaySinh.setText(null);
      }
    }//GEN-LAST:event_txtNgaysinhKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblHt;
    private javax.swing.JLabel lblMakh;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JTable tblGirlview;
    public javax.swing.JTextField txtDiachi;
    public javax.swing.JTextField txtHoten;
    public javax.swing.JTextField txtMakh;
    public javax.swing.JTextField txtNgaysinh;
    public javax.swing.JTextField txtSodt;
    // End of variables declaration//GEN-END:variables
int index = 0;
    KhachHangDAO dao = new KhachHangDAO();

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

     //Bắt lỗi
    public boolean isvalid(){
        if(txtMakh.getText().length() == 0){
            DialogHelper.alert(this, "Không được bỏ trống mã khách hàng!");
            return false;
        }
        if(txtMakh.getText().length() < 3){
            DialogHelper.alert(this, "Mã khách hàng có ít nhất có 3 ký tự!");
            return false;
        }
        if(txtNgaysinh.getText().length() < 3){
            DialogHelper.alert(this, "Ngày sinh không nhâp đúng định dạng!");
            return false;
        }
        return true;
    }
    
    void load() {
        DefaultTableModel model = (DefaultTableModel) tblGirlview.getModel();
        model.setRowCount(0);
        try {
            List<KhachHang> list = dao.select();
            for (KhachHang tl : list) {
                Object[] row = {
                tl.getMaKH(),
                tl.getHoTen(),
                tl.getDiaChi(),
                tl.getSoDienThoai(),
                tl.getNgaySinh()
            };
            model.addRow(row);
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    public boolean insert(){
        KhachHang model = getModel();
        try {
            dao.insert(model);
            this.load();
            this.clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
            return true;
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!");
        }
        return false;
    }
    
    public boolean update(){
        KhachHang model = getModel();
        try {
            dao.update(model);
            this.load();
            DialogHelper.alert(this, "Cập nhật thành công!");
            return true;
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
        return false;
    }

    public boolean delete(){
        if(DialogHelper.confirm(this, "Bạn có muốn xóa hay không?")){
            String MaKH = txtMakh.getText();
            try {
                dao.delete(MaKH);
                this.load();
                this.clear();
                DialogHelper.alert(this, "Xóa thành công!");
                return true;
            }
            catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
        return false;
    }

    void clear(){
        this.setModel(new KhachHang());
        this.setStatus(true);
    }

    void edit() {
        try {
            String MaKH = (String) tblGirlview.getValueAt(this.index, 0);
            KhachHang model = dao.findById(MaKH);
            if(model != null){
            this.setModel(model);
            this.setStatus(false);
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void setModel(KhachHang model){
        txtMakh.setText(model.getMaKH());
        txtHoten.setText(model.getHoTen());
        txtDiachi.setText(model.getDiaChi());
        txtNgaysinh.setText(model.getNgaySinh());
        txtSodt.setText(model.getSoDienThoai());
        lblDC.setText(null);
        lblHt.setText(null);
        lblMakh.setText(null);
        lblNgaySinh.setText(null);
        lblSDT.setText(null);
    }
    
    KhachHang getModel(){
        KhachHang model = new KhachHang();
        model.setMaKH(txtMakh.getText());
        model.setHoTen(txtHoten.getText());
        model.setDiaChi(txtDiachi.getText());
        model.setNgaySinh(txtNgaysinh.getText());
        model.setSoDienThoai(txtSodt.getText());
        return model;
    }

    void setStatus(boolean insertable){
        btnThem.setEnabled(insertable);
        btnSua.setEnabled(!insertable);
        btnXoa.setEnabled(!insertable);
        boolean first = this.index > 0;
        boolean last = this.index < tblGirlview.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    } 
   
}
